paths:
  raw_dir: data/raw
  warehouse_features: data/warehouse/features.parquet
  artifacts_dir: artifacts
  mlruns_dir: mlruns

features:
  count_windows: [5, 10, 20]
  ttl_seconds: 120

model:
  lightgbm:
    objective: binary
    n_estimators: 500
    learning_rate: 0.05
    num_leaves: 63
    max_depth: -1
    max_bin: 255          # <-- fixed typo (was macx_bin)
    min_child_samples: 40 # <-- keep ONLY this; remove min_data_in_leaf to avoid ignore-warning
    subsample: 0.8
    subsample_freq: 1     # <-- using subsample/subsample_freq; do NOT also set bagging_* 
    colsample_bytree: 0.8 # <-- use this; do NOT also set feature_fraction
    reg_alpha: 0.0
    reg_lambda: 0.0
    random_state: 42
    n_jobs: -1
    verbose: -1
    min_split_gain: 0.0   # <-- LightGBM’s name (not min_gain_to_split)

  decision:
    ev_threshold: 0.01
    margin_threshold: 0.015


leagues: ["NBA", "MLB", "NFL"]
books: ["pinnacle", "draftkings", "fanduel"]
markets: ["moneyline"]

betting:
  stake_model: "kelly_fractional"
  kelly_fraction: 0.25
  ev_threshold: 0.01
  bankroll_start: 1000.0

paths:
  vendors: "data/vendors"
  warehouse: "data/warehouse"
  artifacts: "artifacts"
  mlruns: "mlruns"
  reports: "reports"

decisions:
  # minutes before scheduled start; used by labeling
  pregame_offset_min: 30



lgbm:
  params:
    objective: binary
    boosting_type: gbdt
    num_leaves: 31
    learning_rate: 0.05
    feature_fraction: 0.9
    bagging_fraction: 0.9
    bagging_freq: 1
    min_data_in_leaf: 10
  n_splits: 5
  random_state: 42
